[info]
game-name = "TP:GZ"
full-game-name = "The Legend of Zelda: Twilight Princess Debug"
developer-name = "Twilight Princess Community"
full-developer-name = "Speedrun Community"

[src]
iso = "gz2e01.iso"
patch = "patch.asm"
map = "map/Final/Release/frameworkF.map"

[build]
map = "build/GZ2E01.map"
iso = "build/tpgz.iso"

[link]
entries = ["game_loop", "read_controller", "draw", "init"]
base = "0x8046_0000"
libs = ["tpgz.a", "external/libtp_c/libtp_c.a", "external/gcn_c/gcn_c.a"]

[files]
"tpgz/save_files/aeralfos_skip.bin" = "res/save_files/aeralfos_skip.bin"
"tpgz/save_files/boss_bug.bin" = "res/save_files/boss_bug.bin"
"tpgz/save_files/camp.bin" = "res/save_files/camp.bin"
"tpgz/save_files/death_sword_skip.bin" = "res/save_files/death_sword_skip.bin"
"tpgz/save_files/deku_toad.bin" = "res/save_files/deku_toad.bin"
"tpgz/save_files/early_platform.bin" = "res/save_files/early_platform.bin"
"tpgz/save_files/fan_tower.bin" = "res/save_files/fan_tower.bin"
"tpgz/save_files/forest_bit.bin" = "res/save_files/forest_bit.bin"
"tpgz/save_files/goats.bin" = "res/save_files/goats.bin"
"tpgz/save_files/gorge_void.bin" = "res/save_files/gorge_void.bin"
"tpgz/save_files/hugo.bin" = "res/save_files/hugo.bin"
"tpgz/save_files/lakebed_bk_skip.bin" = "res/save_files/lakebed_bk_skip.bin"
"tpgz/save_files/mdh_bridge.bin" = "res/save_files/mdh_bridge.bin"
"tpgz/save_files/norgor.bin" = "res/save_files/norgor.bin"
"tpgz/save_files/onebomb.bin" = "res/save_files/onebomb.bin"
"tpgz/save_files/pillar_clip.bin" = "res/save_files/pillar_clip.bin"
"tpgz/save_files/poe_1_skip.bin" = "res/save_files/poe_1_skip.bin"
"tpgz/save_files/stallord.bin" = "res/save_files/stallord.bin"
"tpgz/save_files/purple_mist.bin" = "res/save_files/purple_mist.bin"
"tpgz/save_files/ordon_gate_clip.bin" = "res/save_files/ordon_gate_clip.bin"
"tpgz/save_files/ems.bin" = "res/save_files/ems.bin"
"tpgz/save_files/forest_escape.bin" = "res/save_files/forest_escape.bin"
"tpgz/save_files/lanayru_gate_clip.bin" = "res/save_files/lanayru_gate_clip.bin"
"tpgz/save_files/karg.bin" = "res/save_files/karg.bin"
"tpgz/save_files/eldin_twilight.bin" = "res/save_files/eldin_twilight.bin"
"tpgz/save_files/iza.bin" = "res/save_files/iza.bin"
"tpgz/save_files/spr_warp.bin" = "res/save_files/spr_warp.bin"
"tpgz/save_files/spr.bin" = "res/save_files/spr.bin"
"tpgz/save_files/lakebed_2.bin" = "res/save_files/lakebed_2.bin"