[package]
name = "fonts"
version = "0.1.0"
authors = ["Cristobal Hall-Ramos <crishallramos@yahoo.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
worker = { git = "https://github.com/hallcristobal/gcn-fonts" }