name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: pheenoh/devkitppc-gcn:latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.2.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Run Make
      run: make